# Generated by Django 5.1.2 on 2024-10-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transakcje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transakcja',
            name='opis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='transakcja',
            name='typ',
            field=models.CharField(max_length=10),
        ),
    ]
